### ISSUE TITLE
42sh empêche le fonctionnement de certaines commandes

### ISSUE THREAD

**Issue by KeroK127** [Ant0wan/42sh#1]
Des commandes comme cat fonctionnent mal lorsque lancées avec 42sh.
la commande `as` fait crasher 42sh.

Comment reproduire : 
- Taper 'cat' dans 42sh

Causes possibles : 
- Le module input conserve le mode canonique entre deux executions de commandes

Je mets une issue quand même au cas ou vous auriez des suggestions, et puis je dois finir d'autres choses d'autres choses avant de chercher d'ou vient ce bug

**Comment by G89Cl215** [comment]
Il faut certainement changer le mode de saisie du terminal en lors de l'exécution d'un binaire. Un peu de la même manière dont on l'init pour lire les termcaps. C'est aussi comme ça que tu peux interrompre un processus fils au clavier. J'avais fait une fonction similaire dans mon 21sh.
