### ISSUE TITLE
Est-ce une vraie issue ?

### ISSUE THREAD

**Issue by G89Cl215** [Ant0wan/42sh#7]
J'ai eu un petit problème de compilation sur ma machine virtuelle: un Debian version 9.5
Ca pourrait tout aussi bien être un problème de package ?

main                     object built
error                    object built
signals                  object built
src/input/input.c:20:18: fatal error: term.h: No such file or directory
 #include <term.h>
                  ^
compilation terminated.
Makefile:40: recipe for target 'src/input/input.o' failed
make: *** [src/input/input.o] Error 1

**Comment by Ant0wan** [comment]
sudo apt-get install libncurses5-dev

**Comment by G89Cl215** [comment]
Tout va bien, merci les gars !
