### ISSUE TITLE
Bad return value cas: env -K

### ISSUE THREAD

**Issue by Ant0wan** [Ant0wan/42sh#8]
env bad option returns 1 instead of 125
```
~/42sh$ env -K
21sh: env: -K: invalid option.
21sh: env: usage: env [name[=value] ...] [-i [command]]
~/42sh$ echo $?
1
```
bash --posix output
```
bash-5.0$ env -K
env: invalid option -- 'K'
Try 'env --help' for more information.
bash-5.0$ echo $?
125
```

**Comment by Taiwing** [comment]
Changed the return in case of bad option to 2. Since env is a builtin, it seems more consistent to make it return the same error code as all other builtins in this case.
